[package]
name = "goagain"
version = "0.1.0"
authors = ["Andreas Vinter-Hviid <andreas.vinterhviid@gmail.com>"]
doc = false

[dependencies]
cairo-rs = "0.0.8"
gdk = "0.3.0"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_10"]
